arr1=[1,2,3,4,5,7]
// const val1=arr1.map((x)=>x+1)
// const val2=arr1.filter((x)=>x+2)
// const val3=arr1.reduce((x)=>x+4)
// console.log(val1)
// console.log(val2)
// console.log(val3)

// const val4=arr1.map((x,y)=>console.log(x,y))
// console.log("next Line")
// const val5=arr1.filter((x,y)=>console.log(x,y))
// console.log("next Line")
// const val6=arr1.filter((x,y)=>console.log(x,y))
// console.log("next Line")
// console.log(val4)
// console.log(val5)
// console.log(val6)

// const val7=arr1.map((x,y,z,)=>console.log(x,y,z,))
// console.log("next Line")
// const val8=arr1.filter((x,y,z,)=>console.log(x,y,z,))
// console.log("next Line")
// const val9=arr1.filter((x,y,z,)=>console.log(x,y,z,))
// console.log("next Line")
// console.log(val7)
// console.log(val8)
// console.log(val9)

const val1=arr1.map((x)=>x>1)
const val2=arr1.filter((x)=>x>2)
const val3=arr1.reduce((x)=>x>1)
console.log(val1)
console.log(val2)
console.log(val3)

